version: '3.7'

services:
  web:
    build: .
    container_name: kodeeducation_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ENVIRONMENT=docker
      - DATABASE_URL="postgresql+asyncpg://postgres:password@db:5432/KodeEducation"

  db:
    image: postgres:15
    container_name: kodeeducation_db
    environment:
      POSTGRES_DB: KodeEducation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
